SELECT TOP (10) [Id]
      ,[UserName]
      ,[Title]
      ,[Email]
      ,[PhoneNumber]
      ,[PhoneExtension]
      ,[Created]
      ,[Updated]
      ,[CreatedBy]
      ,[UpdatedBy]
      ,[FirstName]
      ,[LastName]
  FROM [dbo].[AdminApplicationUsers]